EntityFrameworkCtis/Models/Contato.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace EntityFrameworkCtis.Models
{
    public class Contato
    {
        public Contato()
        {
            Enderecos = new List<Endereco>();
        }
        public int ContatoId { get; set; }
        public string Nome { get; set; }
        public string Telefone { get; set; }
        public DateTime DataNascimento { get; set; }
        public string email { get; set; }
        public virtual ICollection<Endereco> Enderecos { get; set; }
    }
}

EntityFrameworkCtis/Controllers/ContatoController.cs
using EntityFrameworkCtis.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EntityFrameworkCtis.Controllers
{
    public class ContatoController : Controller
    {
        private DataContext db = new DataContext();

        // GET: Contato
        public ActionResult Index()
        {
            List<Contato> contatos = db.Contato.Include("Enderecos").ToList();

            return View(contatos);
        }

        // GET: Contato/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Contato/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Contato/Create
        [HttpPost]
        public ActionResult Create(Contato contato)
        {
            if (contato.DataNascimento.ToString() == "01/01/0001 00:00:00")
            {
                this.ModelState.AddModelError("DataNascimento", "Data Inválida");
                return View(contato);
            }

            try
            {
                db.Contato.Add(contato);
                db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch (DbEntityValidationException ex)
            {
                var error = ex.EntityValidationErrors.First().ValidationErrors.First();
                this.ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
                return View(contato);
            }
        }

        // GET: Contato/Edit/5
        public ActionResult Edit(int id)
        {
            Contato contato = db.Contato.Include("Enderecos").Where(x => x.ContatoId == id).FirstOrDefault();

            ViewBag.ContatoId = contato.ContatoId;
            ViewBag.Enderecos = contato.Enderecos;

            return View(contato);
        }

        // POST: Contato/Edit/5
        [HttpPost]
        public ActionResult Edit(Contato model)
        {
            Contato contato = db.Contato.Include("Enderecos").Where(x => x.ContatoId == model.ContatoId).FirstOrDefault();
            contato.Nome = model.Nome;
            contato.Telefone = model.Telefone;
            contato.email = model.email;
            if(model.DataNascimento.ToString() == "01/01/0001 00:00:00")
            {
                this.ModelState.AddModelError("DataNascimento", "Data Inválida");
                return View(contato);
            }
            contato.DataNascimento = model.DataNascimento;

            try
            { 
                db.Entry(contato).State = EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("Edit", model.ContatoId);
            }
            catch (DbEntityValidationException ex)
            {
                var error = ex.EntityValidationErrors.First().ValidationErrors.First();
                this.ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
                return View(contato);
            }
        }

        // GET: Contato/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Contato/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

EntityFrameworkCtis/Controllers/EnderecoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EntityFrameworkCtis.Models;
using System.Data.Entity.Validation;

namespace EntityFrameworkCtis.Controllers
{
    public class EnderecoController : Controller
    {
        private DataContext db = new DataContext();

        // GET: Endereco
        public ActionResult Index()
        {
            var endereco = db.Endereco.Include(e => e.Contato);
            return View(endereco.ToList());
        }

        // GET: Endereco/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Endereco endereco = db.Endereco.Find(id);
            if (endereco == null)
            {
                return HttpNotFound();
            }
            return View(endereco);
        }

        // GET: Endereco/Create
        public ActionResult Create(int id)
        {
            ViewBag.ContatoId = id;

            Endereco endereco = new Endereco();
            endereco.ContatoId = id;

            return View(endereco);
        }

        // POST: Endereco/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Endereco endereco)
        {
            try
            {
                db.Endereco.Add(endereco);
                db.SaveChanges();
                return RedirectToAction("Edit", "Contato", new { id = endereco.ContatoId });
            }
            catch (DbEntityValidationException ex)
            {
                var error = ex.EntityValidationErrors.First().ValidationErrors.First();
                this.ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
                return View(endereco);
            }
        }

        // GET: Endereco/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Endereco endereco = db.Endereco.Find(id);
            if (endereco == null)
            {
                return HttpNotFound();
            }

            return View(endereco);
        }

        // POST: Endereco/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Endereco endereco)
        {
            try
            {
                db.Entry(endereco).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Edit", "Contato", new { id = endereco.ContatoId });
            }
            catch (DbEntityValidationException ex)
            {
                var error = ex.EntityValidationErrors.First().ValidationErrors.First();
                this.ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
                return View(endereco);
            }
        }

        // GET: Endereco/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Endereco endereco = db.Endereco.Find(id);
            if (endereco == null)
            {
                return HttpNotFound();
            }
            return View(endereco);
        }

        // POST: Endereco/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Endereco endereco = db.Endereco.Find(id);
            db.Endereco.Remove(endereco);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EntityFrameworkCtis/Views/Contato/Create.cshtml
@model EntityFrameworkCtis.Models.Contato

@{
    ViewBag.Title = "Create";
}

<h2>Cadastro de Contato</h2>

@using (Html.BeginForm("Create", "Contato", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataNascimento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataNascimento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataNascimento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </div>

        <div>
            <p style="font-weight:bold">
                <i class="glyphicon glyphicon-arrow-left" title="Voltar" style="color:dodgerblue"></i> @Html.ActionLink("Voltar", "Index", "Contato")
            </p>
        </div>
    </div>
}

EntityFrameworkCtis/Views/Contato/Edit.cshtml
@model EntityFrameworkCtis.Models.Contato

@{
    ViewBag.Title = "Create";
}

<h2>Edição de Contato</h2>

@using (Html.BeginForm("Edit", "Contato", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.HiddenFor(model => Model.ContatoId)
    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataNascimento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataNascimento, new { htmlAttributes = new { @class = "form-control", id = "datanasc" } })
                @Html.ValidationMessageFor(model => model.DataNascimento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Atualizar" class="btn btn-primary" />
            </div>
        </div>
        <hr />
        <table>
            <tr>
                <td style="padding-left:15px">
                    <a href="@Url.Action("Create", "Endereco", new { id = Model.ContatoId })" class="btn btn-primary" style="font-weight:bold"><i class="glyphicon glyphicon-plus" title="Adicionar Endereço"></i> Adicionar Endereço</a>
                </td>
            </tr>
        </table>

    </div>
}

<div>
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Rua</th>
                <th>Número</th>
                <th>Bairro</th>
                <th>CEP</th>
                <th>Complemento</th>
                <th>Cidade</th>
                <th>Estado</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var endereco in Model.Enderecos)
            {
                <tr>
                    <td>@endereco.EnderecoId</td>
                    <td>@endereco.Rua</td>
                    <td>@endereco.Numero</td>
                    <td>@endereco.Bairro</td>
                    <td>@endereco.CEP</td>
                    <td>@endereco.Complemento</td>
                    <td>@endereco.Cidade</td>
                    <td>@endereco.Estado</td>               
                    <td>
                        <a href="@Url.Action("Edit", "Endereco", new { id = endereco.EnderecoId })" style="font-weight:bold"><i class="glyphicon glyphicon-edit" title="Adicionar Cotação"></i> Editar</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<div>
    <p style="font-weight:bold">
        <i class="glyphicon glyphicon-arrow-left" title="Voltar" style="color:dodgerblue"></i> @Html.ActionLink("Voltar", "Index", "Contato")
    </p>
</div>

EntityFrameworkCtis/Views/Contato/Index.cshtml
@model IList<EntityFrameworkCtis.Models.Contato>

@{
    ViewBag.Title = "Index";
}

<h2>Contatos</h2>

<p>
    <a href="@Url.Action("Create", "Contato")" style="font-weight:bold"><i class="glyphicon glyphicon-plus" title="Cadastrar Contato"></i> Cadastrar Contato</a>
</p>

<div>
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nome</th>
                <th>Email</th>
                <th>Telefone</th>
                <th>Data de Nascimento</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var contato in Model)
            {
                <tr>
                    <td>@contato.ContatoId</td>
                    <td>@contato.Nome</td>
                    <td>@contato.email</td>
                    <td>@contato.Telefone</td>
                    <td>@contato.DataNascimento</td>
                    <td>
                        <a href="@Url.Action("Edit", "Contato", new { id = contato.ContatoId })" style="font-weight:bold"><i class="glyphicon glyphicon-edit" ></i> Editar</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>